project:
  type: website
  output-dir: docs

website:
  title: "My Personal Website"
  navbar:
    left:
      - href: index.qmd
        text: Introduction
      - href: project.qmd
        text: Project
      - href: movie.qmd
        text: Movie
      - href: reflection.qmd
        text: Reflection

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



